Refactor bottomNavigationBar parameter of HomePage.
Kelv1nG/iskulapp-flutter pull request #1
Opened 2024-11-23 04:18 UTC by georgecabaccang

- Extract NavigationBar widget to its own class called BottomNavigation.
- Create BottomNavDestination class where the NavgationDestination list is.
- Use BottomNavDestinations as value for destinations parameter of BottomNavigation in HomePage.

2024-11-23 04:46 UTC, Kelv1nG commented on lib/pages/home/utils/bottom_nav/bottom_navigation.dart
> +typedef VoidCallbackWithArg = void Function(int);
its ok to use inline here as long as the type def is simple enough

https://dart.dev/effective-dart/design#prefer-inline-function-types-over-typedefs

2024-11-23 04:47 UTC, Kelv1nG approved these changes

2024-11-23 04:52 UTC, georgecabaccang commented on lib/pages/home/utils/bottom_nav/bottom_navigation.dart
> +typedef VoidCallbackWithArg = void Function(int);
Resolved.

2024-11-23 16:44 UTC, Kelv1nG commented on lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart
> +              createSlideRoute(ChangePasswordPage()),
convert to stateless widget

2024-11-23 16:44 UTC, Kelv1nG commented on lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart
> +}
convert to stateless widget

2024-11-23 16:46 UTC, Kelv1nG commented on lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart
> +}
convert to stateless widget

2024-11-23 16:48 UTC, Kelv1nG requested changes
requesting changes

2024-11-24 06:33 UTC, georgecabaccang commented on lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart
> +}
Resolved. 
Fix is here: ef785e57de9168a529674bc33d4557157f5b5bfe
File: 
- **lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart**

2024-11-24 06:33 UTC, georgecabaccang commented on lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart
> +}
Resolved. 
Fix is here: ef785e57de9168a529674bc33d4557157f5b5bfe
File: 
- **lib/pages/home/app_body/views/settings/widgets/helpers/settings_list.dart**

2024-11-26 06:30 UTC, merged