Refactor TimeTablePage and related files.
Kelv1nG/iskulapp-flutter pull request #17
Opened 2024-12-10 14:50 UTC by georgecabaccang

### 📝 Updates

#### Note worthy:
- Create divider for general use.
- Create timetable.dart.
- Create DaysOfTheWeek enum for consistent day values.
- Create ClassDetails class for consistent class details. (sub, teacher, etc..)
- Create Timetable class to encapsulate DaysOfTheWeek and ClassDetails for better typing. (Map<String, dynamic>? timetableData; -> late Timetable? timeTable;)
- Remove 'Timetable' key from timetable.json and expose the days directly.
- Refactor TimetableCard into a pure card widget and use CustomItemCard.
- Create CustomListView for more uniform general listviews.
- Create TimetableList and CustomListView.
- Configure TimeTableTabBar to be more reusable.
- Create StringValues interface with regards to new configuration of TimeTableTabBar.
- Add 'shortened' getter to DaysOfTheWeek with regards to new configuration of TimeTableTabBar.
- Remove Expanded widget in CustomListView to remove minor display exception/bug.

2024-12-11 13:21 UTC, Kelv1nG commented on lib/pages/timetable/helpers/timetable.dart
> +}
change implementation of value / display string similar to enums in lib/enums

2024-12-11 13:29 UTC, Kelv1nG commented on lib/pages/timetable/widget/timetable_list.dart
> +    final List<ClassDetails> classes;
can removed generic T as it is unused(?)

2024-12-11 13:35 UTC, Kelv1nG commented on lib/pages/timetable/widget/timetable_tabbar.dart
> +    final List<T> tabs;
will this be used other than the subject class schedule?
If no probably just use a concrete type for List<T> tabs

2024-12-11 13:36 UTC, Kelv1nG requested changes
please check/comment on requested changes

2024-12-11 16:19 UTC, ejempic approved these changes

2024-12-12 03:30 UTC, georgecabaccang commented on lib/pages/timetable/widget/timetable_list.dart
> +    final List<ClassDetails> classes;
Resolved. My bad.
Changes here: [6c119de](https://github.com/Kelv1nG/iskulapp-flutter/pull/17/commits/6c119debf0bb73ec7b53637cd2eb8376845f3d28)

2024-12-12 03:31 UTC, georgecabaccang commented on lib/pages/timetable/widget/timetable_tabbar.dart
> +    final List<T> tabs;
Changed it into reusable TabBar.
Changes here: [091d2c2](https://github.com/Kelv1nG/iskulapp-flutter/pull/17/commits/091d2c2c74e18c68809de64b688a2b764d049d2f)

2024-12-12 03:36 UTC, georgecabaccang commented on lib/pages/timetable/helpers/timetable.dart
> +}
Resolved. Thank you for pointing this out.
Changes here: [e4dec7c](https://github.com/Kelv1nG/iskulapp-flutter/pull/17/commits/e4dec7c2203b7b63a93d0a818bb8e557b25ff29f)

2024-12-12 03:37 UTC, georgecabaccang commented on lib/pages/common_widgets/dividers/general_divider.dart
> +                : 0);
Resolved. Sorry for the eyesore.
Changes here: [0361b54](https://github.com/Kelv1nG/iskulapp-flutter/pull/17/commits/0361b54a8d4aeaac4f27629679c006a394e12b99)

2024-12-12 10:30 UTC, merged