Feature/attendance
Kelv1nG/iskulapp-flutter pull request #18
Opened 2024-12-14 07:51 UTC by georgecabaccang

### 🎫 Ticket

- [18-add-pr-template](https://github.com/FredMadrona/nextJS-HardwaresPH/pull/1)

### 📦 Packages

- List all the packages added or removed in this PR.

### 📝 Updates

- List all the updates that you made. If you have a UI update please include a screenshot of the update.

### 🧪 Testing Steps

- List the testing steps for this update.

2025-01-07 13:24 UTC, Kelv1nG commented on lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart
> +    List<EntityDisplayData> filters = FilterByType.values.toList();
i think List<EntityDisplayData> would be alright if "filters" could have other types other than FilterByType 
but for current implementation:

List<FilterByType> filters = FilterByType.values;

seems more straightforward

2025-01-08 00:41 UTC, Kelv1nG commented on lib/pages/attendance/attendance_calendar/helpers/classes/attendance_details.dart
> +            ),
create separate function for this

2025-01-08 01:08 UTC, Kelv1nG commented on lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart
> +    void _onChangePerson(EntityDisplayData? person) {
value / displayName from EntityDisplayData is not used.

might be better to change to
```
  void _onChangePerson(MockStudent student) {
    if (student == null) {
      return setState(() => attendanceDetails = {});
    }
      List<AttendanceDetails> studentAttendanceRecord = attendanceStudent
          .where((attendance) => attendance.studentId == person.id)
          .toList();
      return setState(() => attendanceDetails =
          ConvertedAttendanceDetails.fromAttendanceList(studentAttendanceRecord)
              .dateDetails);
    }
  }
```

2025-01-08 01:44 UTC, Kelv1nG commented on lib/pages/attendance/attendance_calendar/widgets/attendance_filters.dart
> +    final ValueChanged<EntityDisplayData?> changePersonFilter;
if we use EntityDisplayData here one would think that any model/entity that implements EntityDisplayData could be used here, but in reality there is only a single type that will be used for ValueChanged<EntityDisplayData> which is  ValueChanged<Student>

2025-01-08 01:47 UTC, Kelv1nG reviewed
please check remarks

2025-01-08 02:08 UTC, Kelv1nG requested changes
please check remarks

2025-01-09 15:08 UTC, georgecabaccang commented on lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart
> +    void _onChangePerson(EntityDisplayData? person) {
Resolved.
Fix is [here.](https://github.com/Kelv1nG/iskulapp-flutter/blob/bc6cd771c016444bfd5d1c2c1fb87370e3f5653d/lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart#L146-#L152)

2025-01-09 15:12 UTC, georgecabaccang commented on lib/pages/attendance/attendance_calendar/helpers/classes/attendance_details.dart
> +            ),
Resolved.
Fix is [here.](https://github.com/Kelv1nG/iskulapp-flutter/blob/7cf281c96408246e34413485585486bc01bfe17b/lib/models/attendance.dart#L78-#L87
)
Thank you for pointing this out.

2025-01-09 15:15 UTC, georgecabaccang commented on lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart
> +    List<EntityDisplayData> filters = FilterByType.values.toList();
Resolved.
Fix is [here.](https://github.com/Kelv1nG/iskulapp-flutter/blob/1a351e29e3e1563a3ff97b87131fdd7f26604b3e/lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart#L46-#L47
)

2025-01-09 15:16 UTC, georgecabaccang commented on lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart
> +    EntityDisplayData? filterBy;
Resolved.
Fix is [here.](https://github.com/Kelv1nG/iskulapp-flutter/blob/1a351e29e3e1563a3ff97b87131fdd7f26604b3e/lib/pages/attendance/attendance_calendar/attendance_calendar_page.dart#L46-#L47
)

2025-01-09 15:18 UTC, georgecabaccang commented
Request for changes resolved. Thank you for reviewing my commits and pointing out my mistakes.

2025-01-14 04:11 UTC, Kelv1nG approved these changes

2025-01-14 08:17 UTC, merged