feature: teacher attendance taking
Kelv1nG/iskulapp-flutter pull request #19
Opened 2024-12-16 05:38 UTC by Kelv1nG

### 🎫 Ticket

- [feature: teacher attendance taking](https://trello.com/c/fgeGJwXM/89-teacher-attendance-checking-integration)

### 📦 Packages

- None

### 📝 Updates
main:
create / update attendance page + integration:
- write operation is handled after radio button select (there is no submit form), in the case of late after 'time_in' declaration

minor:
- added time related utils for parsing / formatting
- update auth utils for easier usage

demo_clip:
https://drive.google.com/file/d/182b1ahWF2KpCchB-hue6Lt6TAeNrY0cM/view?usp=drive_link

depends on below PR:
https://github.com/Kelv1nG/iskulapp-laravel/pull/32

### 🧪 Testing Steps

- Only checked in app

2024-12-16 07:11 UTC, georgecabaccang requested changes

2024-12-16 07:11 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/attendance_create_update_form.dart
> +            children: [
Please change to

```@override
  Widget build(BuildContext context) {
    if (isLoading) {
         return const Center(
               child: CircularProgressIndicator(),
         );
   }
   return Column( . . .

2024-12-16 07:11 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/attendance_create_update_page.dart
> +}
Please move this into its own file.

2024-12-16 07:43 UTC, ejempic commented on lib/models/student.dart
> +import 'package:powersync/sqlite3_common.dart' as sqlite;
love this

2024-12-16 07:44 UTC, ejempic approved these changes
LGTM

2024-12-16 07:49 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/widgets/attendance_filter.dart
> +        const SizedBox(width: 30),
Please change to a more responsive unit using MediaQuery.

2024-12-16 07:49 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/widgets/filter/date_selector.dart
> +      },
Please extract the async function out of the build method to avoid recreating the function on each rebuild.
Also, it'll make the build function more readable as a bonus.

2024-12-16 07:49 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/widgets/filter/section_filter.dart
> +          borderSide: BorderSide(color: Colors.grey),
Please use AppColors for uniformity. (When remembered. No big deal. Can be changed later/ when seen. Haha.)

2024-12-16 13:03 UTC, Kelv1nG commented on lib/pages/attendace/attedance_create_update/attendance_create_update_form.dart
> +            children: [
the problem with if-else statement in widgets are they are not single expressions
but can easily allow for multiple expressions to be inside

```
Widget build(BuildContext context) {
  if (someCondition) {
      // insert some other logic for rendering
  }
}

```

where as ternary operators you couldnt easily do something like above due to readability issues in chaining ternary operations

2024-12-19 11:56 UTC, Kelv1nG commented on lib/pages/attendace/attedance_create_update/attendance_create_update_form.dart
> +  }
changes at [82f](https://github.com/Kelv1nG/iskulapp-flutter/pull/19/commits/82f6e419fea54aa0abb27986e32c88c8c51ec84b)

2024-12-19 11:58 UTC, Kelv1nG commented on lib/pages/attendace/attedance_create_update/widgets/attendance_filter.dart
> +        const SizedBox(width: 30),
changes at [f69](https://github.com/Kelv1nG/iskulapp-flutter/pull/19/commits/f69b47d1b91016a4624b95209492be91fabc09b8)

2024-12-19 11:59 UTC, Kelv1nG commented on lib/pages/attendace/attedance_create_update/widgets/filter/date_selector.dart
> +      },
changes at [78fb499](https://github.com/Kelv1nG/iskulapp-flutter/pull/19/commits/78fb49979ba2c98068c01c2ef1c4d81464f6c464)

2024-12-19 12:01 UTC, Kelv1nG commented on lib/pages/attendace/attedance_create_update/widgets/filter/section_filter.dart
> +          borderSide: BorderSide(color: Colors.grey),
changes at [6c9dbe8](https://github.com/Kelv1nG/iskulapp-flutter/pull/19/commits/6c9dbe8b06d15df874fbfc9edbb6ed887c8bbfca)

2024-12-19 15:01 UTC, georgecabaccang commented on lib/pages/attendace/attedance_create_update/attendance_create_update_form.dart
> +    }
Nice. Forgot about finally. Will be doing this as well. Thank you.

2024-12-19 15:02 UTC, georgecabaccang approved these changes

2024-12-19 22:02 UTC, merged